version: "3.7"
services:
    react-dev:
        container_name: react-dev
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5004:3000"
        volumes:
            - ".:/app"
            - "/app/node_modules"
        environment:
            - NODE_ENV=development